//
// Created by johan on 02/04/2026.
//

#ifndef REVISED_POWER_QUALITY_WAVEFORM_ANALYSER_WAVEFORM_H
#define REVISED_POWER_QUALITY_WAVEFORM_ANALYSER_WAVEFORM_H

#endif //REVISED_POWER_QUALITY_WAVEFORM_ANALYSER_WAVEFORM_H
